#%RAML 1.0
title: Agent Authorisation Test Support
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]
description: The Agent Authorisation Test Support API prepares Client's data in the stub and returns a knownFact required when creating agent authorisation request using POST /agents/:arn/invitations.

documentation:
 - title: Overview
   content: !include docs/overview.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  headerErrors:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                badRequestUnsupportedVersion:
                    description: Missing or unsupported version found in 'Accept' header.
                    value:
                      code: BAD_REQUEST
                      message: Missing or unsupported version number
                badRequestUnsupportedContentType:
                    description: Missing or unsupported found in 'Accept' header.
                    value:
                      code: BAD_REQUEST
                      message: Missing or unsupported content-type.
        406:
          body:
            application/json:
              type: types.errorResponse
              examples:
                acceptHeaderMissing:
                  description: Missing 'Accept' header.
                  value:
                    code: ACCEPT_HEADER_INVALID
                    message: Missing 'Accept' header.
                acceptHeaderInvalid:
                    description: Invalid 'Accept' header.
                    value:
                      code: ACCEPT_HEADER_INVALID
                      message: Invalid 'Accept' header

/agent-authorisation-test-support:
  /known-facts:
    /mtd-vat/vrn/{vrn}:
      is: [headers.acceptHeader, headerErrors]
      uriParameters:
        vrn:
          description: VAT Registration Number
          type: string
          example: "101747696"
      get:
        displayName: Prepare test data in the stubs and return expected payload for POST /agents/{arn}/invitations

        responses:
          200:
            body:
              application/json:
                description: Returns VAT Registration Date matching client's VRN for the purpose of MTD-VAT agent authorisation request
                type: !include schemas/known-facts.schema.json
                examples:
                  pending and responded: !include examples/known-fact-mtd-vat.json

    /mtd-it/nino/{nino}:
          is: [headers.acceptHeader, headerErrors]
          uriParameters:
            nino:
              description: National Insurance Number
              type: string
              example: AA999999A
          get:
            displayName: Prepare test data in the stubs and return expected payload for POST /agents/{arn}/invitations

            responses:
              200:
                body:
                  application/json:
                    description: Returns business postcode matching client's NINO for the purpose of MTD-IT agent authorisation request
                    type: !include schemas/known-facts.schema.json
                    examples:
                      pending and responded: !include examples/known-fact-mtd-it.json

    /invitations:
      /:id:
          is: [headers.acceptHeader, headerErrors]

          put:
            displayName: Accept an invitation created with POST /agents/{arn}/invitations.

            responses:
              204:
                description: Invitation has been accepted
              404:
                description: Invitation not found for the given id
              409:
                description: Invitation already has been rejected or expired

          delete:
            displayName: Reject an invitation created with POST /agents/{arn}/invitations

            responses:
              204:
                description: Invitation has been rejected.
              404:
                description: Invitation not found for the given id
              409:
                description: Invitation already has been accepted or expired


